import json
import argparse
import sys

def main():
    parser = argparse.ArgumentParser(description="Generate a Markdown Leaderboard from benchmark JSON results.")
    parser.add_argument("--input", type=str, required=True, help="Path to JSON file containing array of benchmark results")
    parser.add_argument("--output", type=str, required=True, help="Path to output Markdown file")

    args = parser.parse_args()

    try:
        with open(args.input, "r") as f:
            data = json.load(f)
    except Exception as e:
        print(f"Failed to load JSON: {e}")
        sys.exit(1)

    # Sort by TPS descending
    data = [d for d in data if d.get("status") == "Success"]
    data.sort(key=lambda x: x.get("tps", 0), reverse=True)

    md_lines = [
        "# LM Studio Model Leaderboard",
        "",
        "| Rank | Model | Context | GPU Ratio | Peak VRAM (GB) | TTFT (s) | TPS |",
        "|---|---|---|---|---|---|---|"
    ]

    for i, row in enumerate(data):
        model = row.get("model", "Unknown")
        ctx = row.get("context_length", 0)
        ratio = row.get("gpu_ratio", 0)
        vram = row.get("peak_vram_gb", "N/A")
        ttft = round(row.get("ttft", 0), 2)
        tps = round(row.get("tps", 0), 2)

        md_lines.append(f"| {i+1} | `{model}` | {ctx} | {ratio} | {vram} | {ttft} | **{tps}** |")

    md_lines.append("\n*Generated by Agentic Optimizer Harness*")

    with open(args.output, "w") as f:
        f.write("\n".join(md_lines))

    print(f"Successfully generated markdown report at {args.output}")

if __name__ == "__main__":
    main()
